import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import RegionsPath from '@/components/regionsPath';
import Hero from '@/components/Hero';
import About from '@/components/About';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>GDSC WOW 2023</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/svg/circle.svg' />
			</Head>
			<Navbar />
			<main>
				<Hero />
				<About />
				<RegionsPath />
			</main>
			<Footer />
		</>
	);
}
