import Head from 'next/head';
import { Inter } from '@next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import RegionsPath from '@/components/regionsPath';
import Hero from '@/components/Hero';
import About from '@/components/About';
import Hackathon from '@/components/Hackathon';
import { Region, RegionContext } from '@/context/Region.context';
import { useState } from 'react';
import Sponsor from '@/components/Sponsor';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const [currentRegion, setCurrentRegion] = useState<Region | null | undefined>(null);
	return (
		<>
			<Head>
				<title>GDSC WOW 2023</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/svg/circle.svg' />
			</Head>
			<Navbar />
			<main>
				<RegionContext.Provider value={{ current: currentRegion, setRegion: setCurrentRegion }}>
					<Hero />
					<About />
					<RegionsPath />
					<Hackathon />
					<Sponsor />
				</RegionContext.Provider>
			</main>
			<Footer />
		</>
	);
}
